// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW7wb6ZsvrKWW-R49lKjNc00Buo7MhLmg',
    appId: '1:1027157129656:web:1789fe7a84418766bbb74d',
    messagingSenderId: '1027157129656',
    projectId: 'e-commerce-app-5aba6',
    authDomain: 'e-commerce-app-5aba6.firebaseapp.com',
    storageBucket: 'e-commerce-app-5aba6.appspot.com',
    measurementId: 'G-78B90G2FN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhrYCqIv7PS2jboiYLL_5I9DUFbG4uqo',
    appId: '1:1027157129656:android:932eee0d76ada447bbb74d',
    messagingSenderId: '1027157129656',
    projectId: 'e-commerce-app-5aba6',
    storageBucket: 'e-commerce-app-5aba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNIkbuX2tT5Fr-0uUCoPEcO3jThd-TQjk',
    appId: '1:1027157129656:ios:23c604947e29818dbbb74d',
    messagingSenderId: '1027157129656',
    projectId: 'e-commerce-app-5aba6',
    storageBucket: 'e-commerce-app-5aba6.appspot.com',
    iosBundleId: 'com.nabirahmani.eCleanFcm',
  );
}
